server:
  port: 8080
  max-http-header-size: 201400

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/spring_boot_movie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 0
  thymeleaf:
    cache: false
    mode: HTML5
  resources:
    static-locations: classpath:/,classpath:/resources/,classpath:/static/
  data:
    elasticsearch:
      repositories:
        enabled: true
      #cluster-nodes: localhost:9300




mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml

#showSql
logging:
  level:
    com:
      example:
        mapper: debug
  file:
    #name: film.log
    path: src/main/resources/log

pagehelper:
  reasonable: true
  support-methods-arguments: true
  helper-dialect: mysql

